export const descriptiveFields = [
  {
    name: "label",
    type: "text",
    label: "Label",
    required: true,
  },
  {
    name: "code",
    type: "text",
    label: "Code",
    required: true,
  },
  {
    name: "labelShort",
    type: "text",
    label: "Label court",
    required: true,
  },
  {
    name: "periodicity",
    type: "select",
    label: "Périodicité",
    defaultValue: "Daily",
    required: true,
    options: ["Daily", "Weekly", "Monthly", "Yearly"],
  },
  {
    name: "dateStartLimit",
    type: "date",
    label: "Date de début",
    required: true,
    defaultValue: "2024-04-01",
  },
  {
    name: "dateEndLimit",
    type: "date",
    label: "Date de fin",
    required: true,
    defaultValue: "2024-04-27",
  },
  {
    name: "family",
    type: "text",
    label: "Famille",
    required: true,
  },
  {
    name: "onMonday",
    type: "checkbox",
    label: "Lundi",
    required: true,
    defaultValue: true,
  },
  {
    name: "onTuesday",
    type: "checkbox",
    label: "Mardi",
    required: true,
    defaultValue: true,
  },
  {
    name: "onWednesday",
    type: "checkbox",
    label: "Mercredi",
    required: true,
    defaultValue: true,
  },
  {
    name: "onThursday",
    type: "checkbox",
    label: "Jeudi",
    required: true,
    defaultValue: true,
  },
  {
    name: "onFriday",
    type: "checkbox",
    label: "Vendredi",
    required: true,
    defaultValue: true,
  },
  {
    name: "onSaturday",
    type: "checkbox",
    label: "Samedi",
    required: true,
    defaultValue: true,
  },
  {
    name: "onSunday",
    type: "checkbox",
    label: "Dimanche",
    required: true,
    defaultValue: true,
  },
];
